[package]
name = "solana-unified-scheduler-logic"
description = "The Solana unified scheduler logic"
documentation = "https://docs.rs/solana-unified-scheduler-logic"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
qualifier_attr = { workspace = true }
solana-sdk = { workspace = true }
static_assertions = { workspace = true }
[[bench]]
name = "bench-with-iai-callgrind"
harness = false

[dev-dependencies]
# See order-crates-for-publishing.py for using this unusual `path = "."`
solana-unified-scheduler-logic = { path = ".", features = ["dev-context-only-utils"] }
triomphe = { version = "0.1.11" }

[target."cfg(target_os = \"linux\")".dev-dependencies]
iai-callgrind = { version = "0.10.2", features = [
    "client_requests"
] }

[target."cfg(not(target_os = \"linux\"))".dev-dependencies]
iai-callgrind = { version = "0.10.2" }

[features]
dev-context-only-utils = []
