[package]
name = "solana-unified-scheduler-pool"
description = "The Solana unified scheduler pool"
documentation = "https://docs.rs/solana-unified-scheduler-pool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
cpu-time = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
log = { workspace = true }
qualifier_attr = { workspace = true }
rustix = { workspace = true }
serde_json = { workspace = true }
solana-ledger = { workspace = true }
solana-measure = { workspace = true }
solana-metrics = { workspace = true }
solana-program-runtime = { workspace = true }
solana-runtime = { workspace = true }
solana-sdk = { workspace = true }
solana-unified-scheduler-logic = { workspace = true }
solana-vote = { workspace = true }

[target."cfg(target_os = \"linux\")".dependencies]
procfs = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
criterion = "0.5.1"
jemallocator = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
solana-logger = { workspace = true }
solana-nohash-hasher = { workspace = true }
solana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
# See order-crates-for-publishing.py for using this unusual `path = "."`
solana-unified-scheduler-pool = { path = ".", features = ["dev-context-only-utils"] }

[[bench]]
name = "lib"
harness = false

[features]
dev-context-only-utils = []
