name: workflow-rustdoc-preview

concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: --enable-index-page -Z unstable-options

jobs:
  job-rustdoc-preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: step-rustup
      uses: dtolnay/rust-toolchain@nightly
    - name: step-apt
      run: sudo apt install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler
    - name: step-cargo
      run: cargo doc --no-deps --document-private-items --package solana-runtime
