name: workflow-windows-build
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: --enable-index-page -Z unstable-options
jobs:
  job-cargo-check-on-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      shell: bash
      run: |
        source ci/rust-version.sh stable
    - name: Build
      id: build
      shell: bash
      run: |
        export OPENSSL_DIR="C:\Program Files\OpenSSL"
        choco install protoc --no-progress
        export PROTOC="C:\ProgramData\chocolatey\lib\protoc\tools\bin\protoc.exe"
        cargo  --config 'patch.crates-io.ntapi.git="https://github.com/solana-labs/ntapi"' --config 'patch.crates-io.ntapi.rev="5980bbab2e0501a8100eb88c12222d664ccb3a0a"' install  --locked spl-token-cli
        cargo check  --locked --workspace --bins --features dummy-for-ci-check
